// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset_tokens.sql

package query

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (user_id, token_digest, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_digest, expires_at, created_at, updated_at
`

type CreatePasswordResetTokenParams struct {
	UserID      uuid.UUID
	TokenDigest string
	ExpiresAt   time.Time
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, createPasswordResetToken, arg.UserID, arg.TokenDigest, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenDigest,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLivePasswordResetToken = `-- name: DeleteLivePasswordResetToken :execrows
DELETE FROM password_reset_tokens WHERE id = $1 AND expires_at > NOW()
`

// 期限内のトークンだけを消し、消せたかどうかでトークンを使えたかを判定する。
func (q *Queries) DeleteLivePasswordResetToken(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLivePasswordResetToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePasswordResetTokensByUserID = `-- name: DeletePasswordResetTokensByUserID :exec
DELETE FROM password_reset_tokens WHERE user_id = $1
`

func (q *Queries) DeletePasswordResetTokensByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePasswordResetTokensByUserID, userID)
	return err
}

const getLivePasswordResetTokenByID = `-- name: GetLivePasswordResetTokenByID :one
SELECT id, user_id, token_digest, expires_at, created_at, updated_at FROM password_reset_tokens WHERE id = $1 AND expires_at > NOW() LIMIT 1
`

func (q *Queries) GetLivePasswordResetTokenByID(ctx context.Context, id uuid.UUID) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, getLivePasswordResetTokenByID, id)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenDigest,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLivePasswordResetTokenByTokenDigest = `-- name: GetLivePasswordResetTokenByTokenDigest :one
SELECT id, user_id, token_digest, expires_at, created_at, updated_at FROM password_reset_tokens WHERE token_digest = $1 AND expires_at > NOW() LIMIT 1
`

func (q *Queries) GetLivePasswordResetTokenByTokenDigest(ctx context.Context, tokenDigest string) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, getLivePasswordResetTokenByTokenDigest, tokenDigest)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenDigest,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
