// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trade_message_reads.sql

package query

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getTradeMessageReadByTradeIDAndUserID = `-- name: GetTradeMessageReadByTradeIDAndUserID :one
SELECT id, trade_id, user_id, last_read_at, last_read_message_id, created_at, updated_at FROM trade_message_reads
WHERE trade_id = $1
  AND user_id = $2
LIMIT 1
`

type GetTradeMessageReadByTradeIDAndUserIDParams struct {
	TradeID uuid.UUID
	UserID  uuid.UUID
}

// ユーザーが交換のメッセージをどこまで読んだか。
func (q *Queries) GetTradeMessageReadByTradeIDAndUserID(ctx context.Context, arg GetTradeMessageReadByTradeIDAndUserIDParams) (TradeMessageRead, error) {
	row := q.db.QueryRowContext(ctx, getTradeMessageReadByTradeIDAndUserID, arg.TradeID, arg.UserID)
	var i TradeMessageRead
	err := row.Scan(
		&i.ID,
		&i.TradeID,
		&i.UserID,
		&i.LastReadAt,
		&i.LastReadMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTradeMessageRead = `-- name: UpsertTradeMessageRead :exec
INSERT INTO trade_message_reads (trade_id, user_id, last_read_at, last_read_message_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (trade_id, user_id) DO UPDATE
SET last_read_at = EXCLUDED.last_read_at,
    last_read_message_id = EXCLUDED.last_read_message_id,
    updated_at = NOW()
WHERE (trade_message_reads.last_read_at, trade_message_reads.last_read_message_id)
    < (EXCLUDED.last_read_at, EXCLUDED.last_read_message_id)
`

type UpsertTradeMessageReadParams struct {
	TradeID           uuid.UUID
	UserID            uuid.UUID
	LastReadAt        time.Time
	LastReadMessageID uuid.UUID
}

// ユーザーが交換のメッセージを、(送信時刻, ID) の位置まで読んだことを記録する。
// 古いページを開き直したときなどに戻さないよう、読んだ位置は進めるだけにする。
func (q *Queries) UpsertTradeMessageRead(ctx context.Context, arg UpsertTradeMessageReadParams) error {
	_, err := q.db.ExecContext(ctx, upsertTradeMessageRead,
		arg.TradeID,
		arg.UserID,
		arg.LastReadAt,
		arg.LastReadMessageID,
	)
	return err
}
