// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_two_factor_recovery_codes.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const countUnusedUserTwoFactorRecoveryCodes = `-- name: CountUnusedUserTwoFactorRecoveryCodes :one
SELECT COUNT(*) FROM user_two_factor_recovery_codes WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) CountUnusedUserTwoFactorRecoveryCodes(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnusedUserTwoFactorRecoveryCodes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserTwoFactorRecoveryCode = `-- name: CreateUserTwoFactorRecoveryCode :exec
INSERT INTO user_two_factor_recovery_codes (user_id, code_digest)
VALUES ($1, $2)
`

type CreateUserTwoFactorRecoveryCodeParams struct {
	UserID     uuid.UUID
	CodeDigest string
}

func (q *Queries) CreateUserTwoFactorRecoveryCode(ctx context.Context, arg CreateUserTwoFactorRecoveryCodeParams) error {
	_, err := q.db.ExecContext(ctx, createUserTwoFactorRecoveryCode, arg.UserID, arg.CodeDigest)
	return err
}

const deleteUserTwoFactorRecoveryCodesByUserID = `-- name: DeleteUserTwoFactorRecoveryCodesByUserID :exec
DELETE FROM user_two_factor_recovery_codes WHERE user_id = $1
`

func (q *Queries) DeleteUserTwoFactorRecoveryCodesByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserTwoFactorRecoveryCodesByUserID, userID)
	return err
}

const useUserTwoFactorRecoveryCode = `-- name: UseUserTwoFactorRecoveryCode :execrows
UPDATE user_two_factor_recovery_codes
SET used_at = NOW(), updated_at = NOW()
WHERE user_id = $1 AND code_digest = $2 AND used_at IS NULL
`

type UseUserTwoFactorRecoveryCodeParams struct {
	UserID     uuid.UUID
	CodeDigest string
}

// 未使用のコードだけを使用済みにし、更新できたかどうかでコードを使えたかを判定する。
func (q *Queries) UseUserTwoFactorRecoveryCode(ctx context.Context, arg UseUserTwoFactorRecoveryCodeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, useUserTwoFactorRecoveryCode, arg.UserID, arg.CodeDigest)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
