// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_passwords.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const createUserPassword = `-- name: CreateUserPassword :one
INSERT INTO user_passwords (user_id, password_digest)
VALUES ($1, $2)
RETURNING id, user_id, password_digest, created_at, updated_at
`

type CreateUserPasswordParams struct {
	UserID         uuid.UUID
	PasswordDigest string
}

func (q *Queries) CreateUserPassword(ctx context.Context, arg CreateUserPasswordParams) (UserPassword, error) {
	row := q.db.QueryRowContext(ctx, createUserPassword, arg.UserID, arg.PasswordDigest)
	var i UserPassword
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PasswordDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserPasswordByUserID = `-- name: DeleteUserPasswordByUserID :exec
DELETE FROM user_passwords WHERE user_id = $1
`

func (q *Queries) DeleteUserPasswordByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserPasswordByUserID, userID)
	return err
}

const getUserPasswordByUserID = `-- name: GetUserPasswordByUserID :one
SELECT id, user_id, password_digest, created_at, updated_at FROM user_passwords WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserPasswordByUserID(ctx context.Context, userID uuid.UUID) (UserPassword, error) {
	row := q.db.QueryRowContext(ctx, getUserPasswordByUserID, userID)
	var i UserPassword
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PasswordDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPasswordDigest = `-- name: UpdateUserPasswordDigest :execrows
UPDATE user_passwords
SET password_digest = $2, updated_at = NOW()
WHERE user_id = $1
`

type UpdateUserPasswordDigestParams struct {
	UserID         uuid.UUID
	PasswordDigest string
}

func (q *Queries) UpdateUserPasswordDigest(ctx context.Context, arg UpdateUserPasswordDigestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserPasswordDigest, arg.UserID, arg.PasswordDigest)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
